/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.13
 * Generated at: 2022-03-13 16:31:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class JspTest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("		#show{\r\n");
      out.write("			appearance: auto;\r\n");
      out.write("			user-select: none;\r\n");
      out.write("			white-space: pre;\r\n");
      out.write("			align-items: flex-start;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			cursor: default;\r\n");
      out.write("			box-sizing: border-box;\r\n");
      out.write("			background-color: green;\r\n");
      out.write("			color: white;\r\n");
      out.write("			padding: 1px 6px;\r\n");
      out.write("			border-width: 2px;\r\n");
      out.write("			border-style: outset;\r\n");
      out.write("			border-color: -internal-light-dark(rgb(118, 118, 118), rgb(133, 133, 133));\r\n");
      out.write("			border-image: initial;\r\n");
      out.write("		}\r\n");
      out.write("        body {\r\n");
      out.write("			background-color: aliceblue;\r\n");
      out.write("            margin-top: 2%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        td {\r\n");
      out.write("            padding: 1px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        table {\r\n");
      out.write("        	background-color: #e7de5f;\r\n");
      out.write("        	border : 1px solid;\r\n");
      out.write("        	padding :10px;\r\n");
      out.write("            text-align: -webkit-center;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function showBill(){\r\n");
      out.write("			//alert(\"ok\");\r\n");
      out.write("			let tamt = document.getElementById('tamt');\r\n");
      out.write("			let tdec = document.getElementById('tdec');\r\n");
      out.write("			let sgst = document.getElementById('sgst');\r\n");
      out.write("			let cgst = document.getElementById('cgst');\r\n");
      out.write("			let payamt = document.getElementById('payamt');\r\n");
      out.write("			let prtamt = document.getElementById('prtamt');\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			const PRO1 = document.getElementById('p1prc');\r\n");
      out.write("			const PRO2 = document.getElementById('p2prc');\r\n");
      out.write("			const PRO3 = document.getElementById('p3prc');\r\n");
      out.write("			const PRO4 = document.getElementById('p4prc');\r\n");
      out.write("			const PRO5 = document.getElementById('p5prc');\r\n");
      out.write("\r\n");
      out.write("			let p1 = PRO1.value? parseInt(PRO1.value) : 0;\r\n");
      out.write("			let p2 = PRO2.value? parseInt(PRO2.value) : 0;\r\n");
      out.write("			let p3 = PRO3.value? parseInt(PRO3.value) : 0;\r\n");
      out.write("			let p4 = PRO4.value? parseInt(PRO4.value) : 0;\r\n");
      out.write("			let p5 = PRO5.value? parseInt(PRO5.value) : 0;\r\n");
      out.write("\r\n");
      out.write("			let total = p1+p2+p3+p4+p5;\r\n");
      out.write("			let des = parseFloat(total*0.1);\r\n");
      out.write("			let sgs = parseFloat(total*0.09);\r\n");
      out.write("			let cgs = parseFloat(total*0.09);\r\n");
      out.write("			\r\n");
      out.write("			tamt.value = total.toFixed(2);\r\n");
      out.write("			tdec.value = des.toFixed(2);\r\n");
      out.write("			sgst.value = sgs.toFixed(2);\r\n");
      out.write("			cgst.value = cgs.toFixed(2);\r\n");
      out.write("			console.log(typeof pymt);\r\n");
      out.write("			payamt.value = ((total+sgs+cgs)-des).toFixed(2);\r\n");
      out.write("			prtamt.value = (total+sgs+cgs).toFixed(2);\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<form action=\"CustBill.jsp\" method=\"get\" >\r\n");
      out.write("	<table align=\"center\">\r\n");
      out.write("	<caption><h2>*Customer Bill*</h2></caption>\r\n");
      out.write("	<tr><td>Customer ID</td><td> :  <input type=\"text\" name=\"cid\" id=\"cid\"> </td></tr>\r\n");
      out.write("	<tr><td>Customer Name</td><td> :  <input type=\"text\" name=\"cname\" id=\"cname\"> </td></tr>\r\n");
      out.write("	<tr><td>Customer Phone No</td><td> :  <input type=\"text\" name=\"cpone\" id=\"cpone\"> </td></tr>\r\n");
      out.write("	<tr><td colspan=2><hr /></td> </tr>\r\n");
      out.write("	<tr><td><b>Product Name</b></td><td> :  <b>Price</b> </td></tr>\r\n");
      out.write("	<tr><td> <input type=\"text\" name=\"pname1\" id=\"pname1\"></td><td> :  <input type=\"text\" name=\"p1prc\" id=\"p1prc\"> </td></tr>\r\n");
      out.write("	<tr><td> <input type=\"text\" name=\"pname2\" id=\"pname2\"></td><td> :  <input type=\"text\" name=\"p2prc\" id=\"p2prc\"> </td></tr>\r\n");
      out.write("	<tr><td> <input type=\"text\" name=\"pname3\" id=\"pname3\"></td><td> :  <input type=\"text\" name=\"p3prc\" id=\"p3prc\"> </td></tr>\r\n");
      out.write("	<tr><td> <input type=\"text\" name=\"pname4\" id=\"pname4\"></td><td> :  <input type=\"text\" name=\"p4prc\" id=\"p4prc\"> </td></tr>\r\n");
      out.write("	<tr><td> <input type=\"text\" name=\"pname5\" id=\"pname5\"></td><td> :  <input type=\"text\" name=\"p5prc\" id=\"p5prc\"> </td></tr>\r\n");
      out.write("	<tr><td colspan=2 align=\"center\"> <hr /> <input type=\"button\" value=\"Show\" id=\"show\" onclick=\"showBill()\"> </td> </tr>\r\n");
      out.write("	<tr><td> Total</td><td> :  <input type=\"text\" name=\"tamt\" id=\"tamt\"> </td></tr>\r\n");
      out.write("	<tr><td> Discount </td><td> :  <input type=\"text\" name=\"tdec\" id=\"tdec\"> </td></tr>\r\n");
      out.write("	<tr><td colspan=2><hr /></td> </tr>\r\n");
      out.write("	<tr><td> SGST</td><td> :  <input type=\"text\" name=\"sgst\" id=\"sgst\"> </td></tr>\r\n");
      out.write("	<tr><td> CGST</td><td> :  <input type=\"text\" name=\"cgst\" id=\"cgst\"> </td></tr>\r\n");
      out.write("	<tr><td colspan=2><hr /></td> </tr>\r\n");
      out.write("	<tr><td> Payble Amount</td><td> :  <input type=\"text\" name=\"payamt\" id=\"payamt\"> </td></tr>\r\n");
      out.write("	<tr><td> Print Bill</td><td> :  <input type=\"text\" name=\"prtamt\" id=\"prtamt\"> </td></tr>\r\n");
      out.write("	<tr><td colspan=2><hr /></td> </tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
